# Generated by Django 3.0.8 on 2021-08-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cough', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('shaking_chills', models.BooleanField(default=False)),
                ('fast_heartbeat', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('muscle_pain', models.BooleanField(default=False)),
                ('cyanosis', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('scan', models.ImageField(upload_to='scan_documents')),
                ('is_pneumonia_patient', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
