# Generated by Django 3.0.8 on 2021-08-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='scan',
        ),
        migrations.AddField(
            model_name='question',
            name='pneumonia_point',
            field=models.FloatField(default=0.0),
        ),
    ]
