# Generated by Django 3.0.8 on 2021-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210802_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='xray_scan',
            field=models.BooleanField(default=False),
        ),
    ]
